# Generated by Django 3.2.9 on 2021-12-09 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('CustomerName', models.CharField(max_length=100)),
                ('AnyDeskId', models.IntegerField()),
                ('ApplicationDetails', models.CharField(max_length=100)),
                ('Requirements', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('CompletionDate', models.DateField(null=True)),
                ('staff', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField(null=True)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Newapp.registration')),
            ],
        ),
    ]
