# Generated by Django 3.2.9 on 2021-12-11 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0002_remove_stafftb_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftb',
            name='Registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Newapp.registration'),
        ),
    ]
